redis:
  uri: http://localhost:6379/
aws:
  access_key_id: OVERRIDE_ME
  secret_access_key: OVERRIDE_ME
hasher:
  secret_key: OVERRIDE_ME
google_analytics:
  analytics_id: UA-31572927-1
email:
  from_address: Watchdog.net <info@watchdog.net>
dp_connection:
  host: OVERRIDE_ME
  username: OVERRIDE_ME
  password: OVERRIDE_ME
  database: OVERRIDE_ME
